services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    env_file:
      - ./.env
    networks:
      - vr-photo-share-net
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - vr-photo-share-net
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    networks:
      - vr-photo-share-net

volumes:
  postgres-data:

networks:
  vr-photo-share-net:
    driver: bridge 