services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - vr-photo-share-net
    depends_on:
      - db
      - minio

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - 80:80  # 本番はnginxで80番
    networks:
      - vr-photo-share-net
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    networks:
      - vr-photo-share-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    networks:
      - vr-photo-share-net

volumes:
  postgres-data:
  minio-data:

networks:
  vr-photo-share-net:
    driver: bridge 