services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - vr-photo-share-net
    depends_on:
      - db
      - minio
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - 5173:5173  # 開発用Viteサーバー
    networks:
      - vr-photo-share-net
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations
    env_file:
      - ./.env
    networks:
      - vr-photo-share-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    networks:
      - vr-photo-share-net

volumes:
  postgres-data:
  minio-data:

networks:
  vr-photo-share-net:
    driver: bridge

# 本番用は docker-compose.prod.yml を参照 